### ISSUE TITLE
Front-end snippet with Mutil-file and Reapeater Field

### ISSUE THREAD

**Issue by kidesigner** [WebDevStudios/CMB2-Snippet-Library#7]
Thank you for front-end snippet, but i have some question:

1. Why you dont use Field Type = file ?
2. How to use Mutil-file and Repeater field?
3. Why you dont use $cmb->save_fields() ?

**Comment by jtsternberg** [comment]
I assume you're referring to the [front-end submit snippet](https://github.com/WebDevStudios/CMB2-Snippet-Library/blob/master/front-end/cmb2-front-end-submit.php).
1. `'file'` type uses the media modal. It would take some effort to make sure the user could not see other's uploaded files.
2. Not possible unless you build something custom.
3. Because I don't want all the fields saved as post-meta.. They are already being used for post title, post content, etc.
